Repository stolostron/provider-credential-controller, pull requests merged in 2025-09, with the labels that each got.

#306 move to konflux common pipeline
  .tekton/provider-credential-controller-mce-26-pull-request.yaml
  .tekton/provider-credential-controller-mce-26-push.yaml
  Dockerfile.rhtap
  Makefile.prow
Labels: approved, dco-signoff: yes

#308 move to konflux common pipeline
  .tekton/provider-credential-controller-mce-29-pull-request.yaml
  .tekton/provider-credential-controller-mce-29-push.yaml
Labels: approved, dco-signoff: yes

#309 move to konflux common pipeline
  .tekton/provider-credential-controller-mce-210-pull-request.yaml
  .tekton/provider-credential-controller-mce-210-push.yaml
Labels: approved, dco-signoff: yes, do-not-merge/hold

#310 Add CLAUDE.md documentation
  CLAUDE.md
Labels: dco-signoff: no, ok-to-test
